name: Azure VM Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Azure VM
      run: |
        ssh -i ${{ secrets.AZURE_SSH_KEY }} user@172.174.227.55 "cd /AzureTuto && git pull"

    - name: cat read.me
      run: |
        ssh -i ${{ secrets.AZURE_SSH_KEY }} user@172.174.227.55 "cat READ.md"
